Issue #11
razat249/github-view pull request #14
Opened 2017-04-02 17:40 UTC by andrewchar

2017-04-02 18:28 UTC, razat249 requested changes
Noce work! A little changea required.

2017-04-02 18:28 UTC, razat249 commented on src/components/UserEventsList/UserEventsList.jsx
> +        console.log("Pupu"); /*<- lol wut*/
Just some funny names for debugging :smile_cat:

2017-04-02 18:28 UTC, razat249 commented on src/components/UserEventsList/UserEventsList.jsx
> +                      eventData.data = <p><b>Repo description:</b> No description provided.</p>
Nice fix 👍

2017-04-02 18:28 UTC, razat249 commented on src/components/UserEventsList/UserEventsList.jsx
> +                      eventData.iconColor = "orange";
I think iconColor should be out of this else block.

2017-04-03 00:27 UTC, andrewchar commented
requested changes are complete.

2017-04-03 01:11 UTC, razat249 approved these changes
Nice, keep up the good work :)

2017-04-03 01:12 UTC, merged